import socket
import signal
import sys
import ssl

# Client setup
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Set up SSL context
context = ssl.create_default_context()
# Verify the server's certificate against the specific self-signed cert this
# project generates (see README: `openssl req -x509 ... -out server.cert
# -keyout server.key`). This pins trust to that one certificate rather than
# either trusting nothing (CERT_NONE) or requiring a public CA, which a
# self-signed cert can never satisfy.
#
# check_hostname is left False: the self-signed cert generated by the README's
# openssl command has no guaranteed Subject Alternative Name for "localhost",
# so enabling hostname checking here could break the handshake depending on
# how the cert was generated. Certificate verification (CERT_REQUIRED +
# load_verify_locations) still ensures the peer presents exactly this
# project's certificate.
context.check_hostname = False
context.verify_mode = ssl.CERT_REQUIRED
try:
    context.load_verify_locations("server.cert")
except (FileNotFoundError, ssl.SSLError) as e:
    print(f"Could not load server.cert for TLS verification: {e}")
    print("Make sure server.cert (generated per the README) is present in this directory.")
    sys.exit(1)

# Connect with SSL
try:
    client.connect(('localhost', 5555))
    secure_client = context.wrap_socket(client, server_hostname='localhost')
except Exception as e:
    print(f"Connection error: {e}")
    sys.exit(1)

def signal_handler(sig, frame):
    print("\nShutting down secure client...")
    try:
        secure_client.send("logoff".encode('utf-8'))
        secure_client.close()
    except:
        pass
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)

# Authentication
try:
    response = secure_client.recv(1024).decode('utf-8')
    print(response, end='')  # Print "Username: "
    username = input()
    secure_client.send(username.encode('utf-8'))

    response = secure_client.recv(1024).decode('utf-8')
    print(response, end='')  # Print "Password: "
    password = input()
    secure_client.send(password.encode('utf-8'))

    response = secure_client.recv(1024).decode('utf-8')
    print(response)
    if "Authentication failed" in response:
        secure_client.close()
        sys.exit(0)
except ssl.SSLError as e:
    print(f"SSL Error during authentication: {e}")
    secure_client.close()
    sys.exit(1)
except Exception as e:
    print(f"Error during authentication: {e}")
    secure_client.close()
    sys.exit(1)

# Communication loop
while True:
    try:
        message = input("Enter message: ")
        secure_client.send(message.encode('utf-8'))
        if message.lower() == "logoff":
            break
        response = secure_client.recv(1024).decode('utf-8')
        if not response:
            break
        print(f"Server: {response}")
    except ssl.SSLError as e:
        print(f"SSL Error: {e}")
        break
    except ConnectionResetError:
        print("Connection was reset by the server.")
        break
    except Exception as e:
        print(f"Error: {e}")
        break

secure_client.close()
print("Connection closed.")